### PR TITLE
page-404:

### PR DESCRIPTION
**Pull request by krovostcora**
Things added:
 - page404
 - customized cursor
 - cat animations

### error page :
https://github.com/Arquisoft/wiq_en3b/assets/58918909/034df401-ea26-4a1e-bdeb-dd8176e84756

### animations and cursor :
https://github.com/Arquisoft/wiq_en3b/assets/58918909/c74efab0-ab6b-48f6-a2c5-8fcd1e7583fb

### CODE REVIEW

**Comment by didierrc** [comment]
Good job on those additions!! It seems that e2e tests are not passing :( did you merge your branch with the tests currently on master? I think they are up to date and I don't think that your changes affect on them, so check that out please!

**Comment by krovostcora** [comment]
> Good job on those additions!! It seems that e2e tests are not passing :( did you merge your branch with the tests currently on master? I think they are up to date and I don't think that your changes affect on them, so check that out please!

thanks!) 
Yes, I merged it on master, and they are up-to-date for now, but e2e tests are still not passing. I am trying to figure out what else could be causing the problems ! :)

**Comment by krovostcora** [comment]
e2e tests were failing because of the size of the animations. I've made them smaller.
 
But now I'm not sure if they are not too small to add...?
__________________________
Знімок екрана 2024-04-27 о 05 52 04
Знімок екрана 2024-04-27 о 05 52 20

**Comment by didierrc** [comment]
Thank you for fixing the errors so e2e test passes, but careful because you are uploading the .idea folder and you shouldn't!

**Comment by krovostcora** [comment]
> Thank you for fixing the errors so e2e test passes, but careful because you are uploading the .idea folder and you shouldn't!

thank you for noticing! done :)

**Review by carlosmndzg — APPROVED** [review]

**Pull request merged**
