### PR TITLE
E2E testing

### PR DESCRIPTION
**Pull request by didierrc**
The e2e testing environment has been configured and some tests have been added
to check if business requirements are met:
- Login tests
- Register tests
- Profile tests
- Game tests

More tests are needed for final project like Gameplay, Leaderboard, Changing configuration and History.

### CODE REVIEW

**Review by Raulms29 — APPROVED** [review]
Very good work on the e2e tests.
Just to say something, will it be possible to create a script to run npm install on all of our folders before executing the e2e tests?

**Comment by didierrc** [comment]
> Very good work on the e2e tests. Just to say something, will it be possible to create a script to run npm install on all of our folders before executing the e2e tests?

Doesn't the CI pipeline do that already? I mean. First, should npm install > unitary tests > e2e Tests?

**Comment by didierrc** [comment]
> > Very good work on the e2e tests. Just to say something, will it be possible to create a script to run npm install on all of our folders before executing the e2e tests?
> 
> Doesn't the CI pipeline do that already? I mean. First, should npm install > unitary tests > e2e Tests?

Screenshot_20240409_220330_Firefox

**Comment by Raulms29** [comment]
Yes, I was just refering when we need to run them locally.

**Comment by didierrc** [comment]
> > Very good work on the e2e tests. Just to say something, will it be possible to create a script to run npm install on all of our folders before executing the e2e tests?
> 
> Doesn't the CI pipeline do that already? I mean. First, should npm install > unitary tests > e2e Tests?




> Yes, I was just refering when we need to run them locally.

Oh, we could try to do that for convenience. Put it if you want as an Issue for next deliverable.

**Pull request merged**
