### PR TITLE
Timeout and Number of questions retrieval

### PR DESCRIPTION
**Pull request by didierrc**
It was solved the issue #94
- Timeout for wikidata service if we do not get any response within a period of time. For the moment,
   it simply skips that question generation but could be discussed for other alternatives.
- Now the endpoint retrieves the EXACT number of questions asked.

### CODE REVIEW

**Comment by didierrc** [comment]
BTW, I know tests are needed! I'll do it tomorrow and also, update the OpenAPI documentation with these new features.

**Comment by Raulms29** [comment]
I have taken a look at it and it's seems good.
I believe we should consider to change the timeout to 5 seconds instead, since some of the queries for the image questions may exceed 3 seconds in some cases.
Will it also be possible to try to make a new request with a different template when the first fails?

**Review by Raulms29 — CHANGES_REQUESTED** [review]
You need to review the tests, since some of them are failing

**Comment by didierrc** [comment]
> I have taken a look at it and it's seems good. I believe we should consider to change the timeout to 5 seconds instead, since some of the queries for the image questions may exceed 3 seconds in some cases. Will it also be possible to try to make a new request with a different template when the first fails?

Well, we could try to pick a random template and run again the query, but what if again fails? Do we continue this loop until finding a "good" template? Another option could be to pick the "fastest" ones: like for example, getting the template for quemical questions. What are your thoughts about?

**Comment by Raulms29** [comment]
We could maybe do what you say about picking a fast one, or we can just try only once and, if it fails again not repeat it.

**Comment by didierrc** [comment]
> We could maybe do what you say about picking a fast one, or we can just try only once and, if it fails again not repeat it.

As we discussed, I have taken the approach of taken the fastest template. The one with type "Chemistry"

Screenshot 2024-03-27 143927

**Review by Raulms29 — APPROVED** [review]
👍

**Pull request merged**
