### PR TITLE
Frontend tests

### PR DESCRIPTION
**Pull request by krovostcora**
tests added for:
- Button
- Settings
- AudioButton
- LanguageSelector
- Nav
- FinalResult
- Question
- Input

### CODE REVIEW

**Comment by krovostcora** [comment]
thanks! Made some corrections, now all tests should pass : )

**Review by didierrc — CHANGES_REQUESTED** [review]
Nice work on those tests! Now, If you could please, remove the commented lines you have on some files then everything will be perfect. Those "errors" are commented on SonarClouds on the link of "Issues".

**Comment by IyanRobles** [comment]
> Nice work on those tests! Now, If you could please, remove the commented lines you have on some files then everything will be perfect. Those "errors" are commented on SonarClouds on the link of "Issues".

For reference, the lines are:
https://github.com/Arquisoft/wiq_en3b/blob/7ecb1c46ce15d8210d9fe3142a546b27b16efe18/webapp/src/components/test/AudioButton.test.js#L3
https://github.com/Arquisoft/wiq_en3b/blob/7ecb1c46ce15d8210d9fe3142a546b27b16efe18/webapp/src/components/test/LanguageSelector.test.js#L3

**Comment by krovostcora** [comment]
> Nice work on those tests! Now, If you could please, remove the commented lines you have on some files then everything will be perfect. Those "errors" are commented on SonarClouds on the link of "Issues".



> > Nice work on those tests! Now, If you could please, remove the commented lines you have on some files then everything will be perfect. Those "errors" are commented on SonarClouds on the link of "Issues".
> 
> For reference, the lines are:
> 
> https://github.com/Arquisoft/wiq_en3b/blob/7ecb1c46ce15d8210d9fe3142a546b27b16efe18/webapp/src/components/test/AudioButton.test.js#L3
> 
> 
> https://github.com/Arquisoft/wiq_en3b/blob/7ecb1c46ce15d8210d9fe3142a546b27b16efe18/webapp/src/components/test/LanguageSelector.test.js#L3

Thanks! I've removed the comments

**Review by didierrc — APPROVED** [review]
Everything is in order! Great work. 🚀

**Pull request merged**
