### PR TITLE
Image Questions

### PR DESCRIPTION
**Pull request by Raulms29**
I have added questions that include the url of an image that is needed to answer them.
For now, the questions generated may or may not contain this field, depending if they are based on images or not. In the future we may want to modify our endpoint so it's possible to request  questions not including or only including images.
I also made some changes to the question generator to support the new templates added (3 templates for image based questions).

### CODE REVIEW

**Comment by didierrc** [comment]
I was checking it and seems good. Just a thing. I think you should update the test so we have more coverage on the new code as SonarCloud states. For the rest, seems good.

And for documentation purposes of API, now JSON returns a field "image" right?
```
Response:
{
id: 0,
question: What's the capital of Peru?,
answers: [
{...},{...},{...},{...}
],
correctAnswerId: 1,
image: https://someurl.com
}
```

**Comment by Raulms29** [comment]
I was implementing some tests just right now.
Regarding the API response I made it so a field image is returned when necessary, if the question does not require an image it won't include this field.

**Comment by didierrc** [comment]
> I was implementing some tests just right now. Regarding the API response, I made it so a field image is returned when necessary, if the question does not require an image the response won't include this field.

Ok nice! Once tests are ready, upload them and I'll have a final look into it.

**Comment by didierrc** [comment]
Thank you for removing the code dupication Raúl! I was going to do that because it was kinda of spaguetti code jejeje

**Review by didierrc — APPROVED** [review]
All good to go

**Pull request merged**
